### ISSUE TITLE
Support Xperia Z3 (InCallUI.apk)

### ISSUE THREAD

**Issue by AndroPlus-org** [Harv/XRecorder#2]
Sony divided SemcPhone.apk to TeleService.apk and InCallUI.apk for Xperia Z3 and other new models,
and XRecorder stopped working on them.
Here is apks from Z3.
https://mega.co.nz/#!rhwhDTgT!SlWCkoKLPW6N0qtg9lAvm-ycgNQ3mM2fgIDyiHYxDsk

Xposed log
de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.phone.SomcInCallScreen
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)
	at com.haoutil.xposed.xrecorder.XposedMod.handleLoadPackage(XposedMod.java:46)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
	at android.app.ActivityThread.handleBindApplication(Native Method)
	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1306)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:212)
	at android.app.ActivityThread.main(ActivityThread.java:5137)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: com.android.phone.SomcInCallScreen
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:251)
	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)
	... 18 more
Caused by: java.lang.NoClassDefFoundError: com/android/phone/SomcInCallScreen
	... 22 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.phone.SomcInCallScreen" on path: DexPathList[[zip file "/system/framework/com.sonymobile.cityid.common.jar", zip file "/system/framework/com.sonymobile.home.resourceprovider.jar", zip file "/system/priv-app/TeleService.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	... 22 more

**Comment by Harv** [comment]
0fa4194e85b5aea242c77a8c71894bbeba2fc035
